name: Reading a Text File on Update

on:
  push:
    branches:
      - main
    paths:
      - 'test.txt'

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Read the text file
        run: |
          cat test.txt
